---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/categories/{category_id}/hotels":
    parameters:
    - name: category_id
      in: path
      description: category_id
      required: true
      schema:
        type: integer
    get:
      summary: list all hotels under a category
      tags:
      - Categories
      responses:
        '200':
          description: successful
  "/api/v1/categories":
    get:
      summary: list all categories
      tags:
      - Categories
      responses:
        '200':
          description: successful
    post:
      summary: Creates a category
      tags:
      - Categories
      parameters: []
      responses:
        '201':
          description: category created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                rating:
                  type: integer
              required:
              - name
              - description
  "/api/v1/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: show category details
      tags:
      - Categories
      responses:
        '200':
          description: category not found
    patch:
      summary: update category
      tags:
      - Categories
      parameters: []
      responses:
        '200':
          description: category name updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                rating:
                  type: integer
                  default: 'null'
                  comment: When added, ranges strictly from 1 to 5 inclusive.
              required:
              - name
              - description
    put:
      summary: update category
      tags:
      - Categories
      parameters: []
      responses:
        '200':
          description: success!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                rating:
                  type: integer
              required:
              - name
              - description
    delete:
      summary: delete category
      tags:
      - Categories
      responses:
        '204':
          description: successful
  "/api/v1/hotels/{hotel_id}/reservations":
    parameters:
    - name: hotel_id
      in: path
      description: hotel_id
      required: true
      schema:
        type: string
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/api/v1/hotels/{hotel_id}/reservations/{id}":
    parameters:
    - name: hotel_id
      in: path
      description: hotel_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
    patch:
      summary: update reservation
      responses:
        '200':
          description: successful
    put:
      summary: update reservation
      responses:
        '200':
          description: successful
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
